### ISSUE TITLE
Add flag for EF based scaffolders to allow users to choose between SQL server and SQLite

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#677] opened 2018-01-19 21:14 UTC
Currently EF based scaffolding generates code which registers a `DbContext` in the Startup class always using `SqlServer` as follows:
```cs
 services.AddDbContext<MyDbContext>(options =>
     options.UseSqlServer(Configuration.GetConnectionString("ConnectionName"));
```

Scaffolding should allow the user to choose SQLite or SQLServer 

cc @danroth27 @mlorbetske

**Comment by vijayrkn** [comment] 2020-01-24 18:27
Closing as a dupe of https://github.com/aspnet/Scaffolding/issues/1231

**Closed by vijayrkn** 2020-01-24 18:27 UTC
