### ISSUE TITLE
Extra paren in the scaffolded Create.cshtml Razor Page

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#1057] opened 2019-08-30 20:01 UTC
Scaffold a Razor Pages based on an EF model. The Create page has an extra paren that renders:

![image](https://user-images.githubusercontent.com/1874516/64048291-2d41e600-cb26-11e9-9729-47143ceda660.png)

**Comment by vijayrkn** [comment] 2019-09-20 19:57
Closing since the issue is fixed.

**Closed by vijayrkn** 2019-09-20 19:57 UTC
Labels: bug
