### ISSUE TITLE
[Question] How to change scaffolding classes and register in VS

### ISSUE THREAD

**Issue by vukuze** [aspnet/Scaffolding#650] opened 2017-11-01 10:14 UTC
Hi. I beginner and can't understand how change existing scaffolding classes (fork or inherit) and how register them in VS 2017.
For example, need to create additional folders and classes in area scaffolding.

**Comment by vijayrkn** [comment] 2019-11-09 01:56
Closing as a dupe of this https://github.com/aspnet/Scaffolding/issues/938

**Closed by vijayrkn** 2019-11-09 01:56 UTC
