### ISSUE TITLE
Creating Controller  throws method not found

### ISSUE THREAD

**Issue by nadavbeno** [aspnet/Scaffolding#986] opened 2019-04-23 08:16 UTC
I'm using the new EF core preview,
Trying to create a controller with Views, and get this error:
![image](https://user-images.githubusercontent.com/26343491/56565455-10fecd00-65b9-11e9-8b01-d321ec1e9af2.png)
Any ideas?
Thanks

**Comment by BehzadA** [comment] 2019-05-01 14:20
Duplicate of # #984

**Comment by seancpeters** [comment] 2019-05-08 18:16
A fix will be available in an upcoming release of Visual Studio. Until then, this will be broken with .Net Core 3.0 preview 5 or higher.

**Comment by vijayrkn** [comment] 2019-11-07 17:05
This is fixed in the latest version.

**Closed by vijayrkn** 2019-11-07 17:05 UTC
