### ISSUE TITLE
Scaffolding fails without details on why, when using certain c# language syntax

### ISSUE THREAD

**Issue by Andrioden** [aspnet/Scaffolding#834] opened 2018-07-12 17:45 UTC
Environment: 
- ASP.Net Core 2.1
- Unspecificed C# language in project settings, I believe I earlier had downloaded and "installed" a newer c# (7.3) version. Then removed it from the project because of then also scaffolding failing.
- Visual Studio Community 2017, Windows

This was one I really did **not** like guys! Since the error gives no clue about what is going on I had to backtrack my commits and guess which change broke scaffolding, thankfully i recalled that scaffolding has some internal build mechanism not using same c# version as the current project, and is therefor sensitive to certain c# language syntax, which I assumes is new c# syntax.

```
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

The problematic code was using implied default value `default` vs `default(CancellationToken)`

Does NOT work:
```
public async override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default)
{
  ...
}
```

Does work:
```
public async override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken))
{
   ...
}
```

Suggested fixes/changes from a user perspective:
- (MUST) Validate, then give better error message that code failed validation according to scaffolding build mechanism.
- (MAYBE) Have scaffolding build with same c# version as project (I am on a limb here, I might have missunderstood the tech)

**Comment by seancpeters** [comment] 2018-07-12 19:16
@Andrioden - Thanks for reporting this problem. For the short-term, I have this PR #824 in progress to provide better error messaging. For your situation, the error will look like this:
![image](https://user-images.githubusercontent.com/20912881/42654349-26aec62c-85cd-11e8-96a3-473f8885913f.png)

For the bigger problem of needing scaffolding to build with the same C# version as the project, we will need to look into the issue more, before deciding on a course of action.

**Comment by seancpeters** [comment] 2018-08-31 22:47
#824 will be included in release/2.2

**Comment by jarnmo** [comment] 2018-09-03 14:51
So, is it really so that scaffolding doesn't work if you're using C# 7.3? I've spent couple hours now trying to track down a "Failed to get Project Context for.." error and this seems to be my only real clue atm. And I'm really not going to refactor all of C# 7.2 out of the codebase..

**Comment by Andrioden** [comment] 2018-09-03 19:31
@jarnmo ; I havent tested it allready, but my planned workaround is to copy th DBContext class and relevant model class into another project and scaffold it there. Maybe its viable for you to?

**Comment by jarnmo** [comment] 2018-09-05 08:37
@Andrioden not really. We are pretty much just praying for this to get fixed before we really have to rescaffold. How on earth can a 'stable' first party feature have a limitation of this magnitude. How is it not even communicated anywhere that you can't use scaffolding unless you are happy to stay with C# 7.0 for undefined time. Possibly forever?


I appreciate the work that has gone into this and I hate to whine, but promoting scaffolding as a stable first party supported feature is extremely irresponsible given this limitation.

**Comment by Andrioden** [comment] 2018-09-05 09:19
@jarnmo : I agree with you, its a pretty bad one. And disclaimer just so it was clear: I dont work for or are affiliated with MS or this project, it was just a friendly tip from a fellow asp.net developer! : >

**Comment by jarnmo** [comment] 2018-09-05 15:09
@Andrioden if you mean the #824, it's not really a fix though. Or is the actually issue of the scaffolder not supporting the latest C# features being tracked somewhere as well? @seancpeters ?

**Comment by jarnmo** [comment] 2018-09-21 07:29
@seancpeters is there any ETA on a fix for this? This is a massive issue on a business critical project for us!

**Comment by seancpeters** [comment] 2018-09-21 18:10
@vijayrkn @danroth27

**Comment by vijayrkn** [comment] 2018-09-21 18:14
@seancpeters - Can you check how much work is required to make scaffolding to build with the same C# version as the project.

**Comment by jarnmo** [comment] 2018-10-01 09:40
@seancpeters Any update on this?

Also, should it just work if I add _<LangVersion>latest</LangVersion>_ to all of the .csproj files in the repo and rebuild the tool myself?

**Comment by InsomniumBR** [comment] 2018-10-01 18:13
+1 same problem here. Thanks god I found this post and just lost 30 minutes on it.

**Comment by seancpeters** [comment] 2018-10-05 22:15
You'll also at least need to update the version of Microsfot.CodeAnalysis, which may also require some other package version changes to get a consistent package set. There may also be other required changes.

**Comment by jarnmo** [comment] 2018-10-09 11:55
@Andrioden @InsomniumBR @seancpeters I think I managed to make it work. I started with the release/2.1, set `<LangVersion>latest</LangVersion>` to all the .csprojs, and updated a bunch of packages and frameworks. When running the build.cmd I get the following error:

> ApiCheck.targets(20,5): error : Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'e_sqlite3.dll' or one of its dependencies. The module was expected to contain an assembly manifest

Additionally some of the tests fail and some of them seem to just never complete. However, it still manages to build the .nupkg, I can install it and it seems to work fine for my C# 7.3 projects with latest stable packages and frameworks.

My changes are here: [https://github.com/jarnmo/Scaffolding/blob/release/2.1](https://github.com/jarnmo/Scaffolding/blob/release/2.1), and if you want to try the tool itself, it's here: [https://github.com/jarnmo/Scaffolding/blob/release/2.1/artifacts/build/dotnet-aspnet-codegenerator.2.1.6-rtm-t000.nupkg](dotnet-aspnet-codegenerator.2.1.6-rtm-t000.nupkg)

**Comment by jarnmo** [comment] 2018-10-10 12:44
@Andrioden @InsomniumBR @seancpeters Doesn't look like my changes really help. It just happened that I was testing against a version of our project that the stable scaffolder seems to work for as well.

However, now I actually went through and found the change in our project that caused the scaffolder to start to fail. It looks like generally C# >7.0 features work fine, but I found two patterns that seem to always cause the error discussed in this issue. Both of the examples seem to apply regardless whether they are in your entity classes or somewhere else in your codebase.

Fails
`private object Test => default;`
Succeeds
`private object Test => null;`

Fails
`private object Test() => new object[] { }.Max(Select);
private static object Select(object o) => o;`
Succeeds
`private object Test() => new object[] { }.Max(o => Select(o));
private static object Select(object o) => o;`

**Comment by AndreiGorlov** [comment] 2019-02-21 13:39
Any updates?

**Comment by jarnmo** [comment] 2019-02-22 14:32
I noticed that the scaffolder does now give a helpful error message about the usage of an unsupported language feature. This helps a lot already!

**Comment by seancpeters** [comment] 2019-02-22 21:56
This issue is on our backlog. As noted above, the better messaging for unsupported language features is now live. But additional work to support newer language versions is not yet scheduled.

**Comment by adimosh** [comment] 2019-05-22 15:38
Any progress on this? It is beyond annoying.

**Comment by seancpeters** [comment] 2019-05-22 18:28
@vijayrkn @danroth27

**Comment by Svetomech** [comment] 2019-06-22 18:27
So, nothing C# > 7.0 is supported still if I understand correctly?

**Comment by adimosh** [comment] 2019-06-22 18:30
How can this not be planned? We can only scaffold if we use c# 7 and nothing beyond? How is this a proper product decision?

**Comment by jarnmo** [comment] 2019-06-24 06:55
There was this commit last week, but not sure how far it will take things: https://github.com/aspnet/Scaffolding/commit/919d307943321fea8d57fec44d16ff7ba14a5774

**Comment by vijayrkn** [comment] 2019-06-24 13:38
Yes this PR https://github.com/aspnet/Scaffolding/commit/919d307943321fea8d57fec44d16ff7ba14a5774 should fix this issue for both C#7 & C#8. Closing this issue.

**Closed by vijayrkn** 2019-06-24 13:38 UTC

**Comment by Preecington** [comment] 2019-07-03 07:47
If anyone needs a quick fix to this before the PR merge goes out into an official package, I found installing the following packages makes the scaffolding work again:
```
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.2.0-beta3-final" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.2.0-beta3-final" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.2.0-beta3-final" />
```

**Comment by dedmen** [comment] 2019-07-27 10:38
Quick fix doesn't work for me sadly.
It's complaining about "using declaration" not being supported and it's telling me to switch to language version preview. My project file is already set to preview language version in the csproj.

Also tried code analysis 3.3.0-beta1-final, exact same thing.

I guess I'll just generate it in a new temp project and copy it over instead...

**Comment by LMerpDev** [comment] 2019-08-23 13:37
Too bad to figure out the limitation that C# 7.1 and above features up to 7.3 cannot be used when scaffolding. Feature 'default literal' in my case prevents from creating about several dozens of pages in the project. Refactoring the code base is no option :-(

**Comment by LMerpDev** [comment] 2019-08-23 14:27
> Are you trying with ASP.NET Core 3.0 projects?

No. Currently using VS 2019 with ASP.NET Core 2.2.6 projects

**Comment by OrihuelaConde** [comment] 2019-10-25 15:28
> If anyone needs a quick fix to this before the PR merge goes out into an official package, I found installing the following packages makes the scaffolding work again:
> 
> ```
> <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.2.0-beta3-final" />
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.2.0-beta3-final" />
> <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.2.0-beta3-final" />
> ```

Thanks, you can fix this only with one package (its include the rest of the needed packages )

`<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.3.1" />`

We are using EF Core 2.2.6 and this issue is not fixed.

**Comment by ardalis** [comment] 2019-10-30 13:48
@OrihuelaConde fix with package 3.3.1 worked for me on my netcore2.2 project.

**Comment by sergeii-55** [comment] 2019-11-21 23:11
i'm starting to learn this technology and following all the tutorials Microsoft provide, like: 

https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio

they should include the @OrihuelaConde solution to the tutorial.
works like a charm for me

**Comment by vijayrkn** [comment] 2019-11-22 00:09
You can see that the latest version of the scaffolding package already references 3.3.1 

https://github.com/aspnet/Scaffolding/pull/1170/files

**Comment by FrankCastle666** [comment] 2020-05-17 09:59
I have a similar problem, and still not fixed:
For details:
https://stackoverflow.com/questions/61681173/ms-visual-studio-2019-crash-when-adding-a-new-scaffolding-item

**Comment by vijayrkn** [comment] 2020-05-17 16:04
@pranavkm - Have you seen this error?

`Error NU1202. Package Microsoft.AspNetCore.Razor 2.2.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Razor 2.2.0 does not support any target frameworks.`

**Comment by FrankCastle666** [comment] 2020-05-17 19:35
Hi Vijay:

I have looked into that error: one of the recommendations to avoid it, is to change the target framework. 
I changed to Net Core 3.0 and the error persists.
If you have any other suggestion, I would appreciate it.
Thanks

**Comment by vijayrkn** [comment] 2020-05-17 21:22
The package targets .NETStandard2.0, so the app can netcoreapp2.0 & above.

**Comment by BRB2000** [comment] 2020-05-25 19:35
I still experience this issue with ASP.NET Core 3.1 and Razor Codegen. It doesn't seem to like async Task<T>, as far as I can tell. Is this actually still to be expected, or should this be fixed? Is there an up-to-date workaround?

**Comment by vijayrkn** [comment] 2020-05-25 19:58
@BRB2000 can you confirm the code generation package version in the csproj file?

**Comment by BRB2000** [comment] 2020-05-25 20:10
@vijayrkn thank you for the quick reply! These packages are referenced in the .csproj file:
`    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="3.1.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.6.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.4" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="3.1.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore" Version="3.1.3" />`

**Comment by vijayrkn** [comment] 2020-05-25 20:59
You only need the codegeneration.design package. You can remove the other 2 codegeneration references.

<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration" Version="3.1.3" /><PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore" Version="3.1.3" />

You are on the latest version. Do you have a sample project that reproduces the issue? @deepchoudhery to help with the analysis

**Comment by BRB2000** [comment] 2020-05-26 08:06
I guess I've found the problem :). I turns out that I had one function in my project that had an "ü" character in it, and scaffolding didn't seem to like that. I know that this is generally bad practise, but I didn't worry too much about it, since the application compiled and ran just fine.

**Comment by vijayrkn** [comment] 2020-05-26 21:51
@BRB2000 - Thanks for diagnosing the root cause. @deepchoudhery - Can you see if you can reproduce it with the above steps? If so, we should handle the error better.

**Comment by deepchoudhery** [comment] 2020-05-27 17:16
@BRB2000 what scaffolder were you using?

**Comment by BRB2000** [comment] 2020-05-27 19:09
I was using `Microsoft.WebTools.Scaffolding.Core.ModelBasedCrudRazorPageScaffolder` and `Microsoft.WebTools.Scaffolding.Core.RazorPages.ModelBasedRazorPageScaffolder`.

**Comment by davidbuckleyni** [comment] 2021-02-15 09:34
This is still and Issue today with .net and ef core 5.0.3 Still to this day the dialog shows up with no descriptive error message really Microsoft can this not be updated to a more mean-full message.

Any Ideas @deepchoudhery and @vijayrkn 

![image](https://user-images.githubusercontent.com/5619229/107928774-a9c1c200-6f70-11eb-90eb-7f0ae29155a8.png)

Visual Studio Verison

![image](https://user-images.githubusercontent.com/5619229/107928981-ee4d5d80-6f70-11eb-94e8-719e276583bd.png)

I noticed here looking at my nuget reference that 5.0.3 has not been released yet could that be part of my issue.

https://www.nuget.org/packages/Microsoft.VisualStudio.Web.CodeGeneration.Design/

Here is my project include files

    <ItemGroup>
     <PackageReference Include="AutoMapper" Version="10.1.1" />
     <PackageReference Include="FileHelpers" Version="3.4.2" />
     <PackageReference Include="MegaApiClient" Version="1.8.2" />
     <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="5.0.3" />
     <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.3" />
     <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="5.0.3" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.3" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.3" />
     <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="5.0.3" />
     <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
     <PackageReference Include="MimeTypes" Version="2.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
     </PackageReference>
     <PackageReference Include="NToastNotify" Version="7.0.0" />
     <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.2" />
     <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.0.2" />
     <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.3" NoWarn="NU1605" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.3" NoWarn="NU1605" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.3" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>


  </ItemGroup>

**Comment by OnSive** [comment] 2021-03-06 19:51
@davidbuckleyni 
> I noticed here looking at my nuget reference that 5.0.3 has not been released yet could that be part of my issue.

Thanks to you I've found a small workaround.
Just change all of the nuget package references from `5.0.3` to `5.0.2` and scaffolding worked.

**Comment by Michael-Nurse-Dev** [comment] 2021-06-24 07:46
I am getting this error repeatedly on a new Windows and Visual Studio install on a .Net Core 3.1 Web MVC Template with all the default options selected.

**Comment by danroth27** [comment] 2021-06-24 23:44
@Michael-Nurse-Dev Please open a new GitHub issue with details about how to reproduce the problem you're seeing and we'll take a look.

**Comment by KevinAnass** [comment] 2021-07-08 15:41
I have the same issue but I was using page.razor and code added in page.razor.cs when i move the code to page.razor the Scaffolding work Fine

**Comment by deepchoudhery** [comment] 2021-07-09 16:33
Tracking here - https://github.com/dotnet/Scaffolding/issues/1555. Pretty much the same issue. @KevinAnass
