### ISSUE TITLE
Running the identity scaffolder generates an empty Services folder

### ISSUE THREAD

**Issue by danroth27** [aspnet/Scaffolding#742] opened 2018-04-09 22:59 UTC
Run the identity scaffolder in VS with the layout specified and a new data context. An empty Services folder is created in the identity area.

**Comment by seancpeters** [comment] 2018-08-31 01:34
#857 is a duplicate of this issue. Closing this, the other has more discussion.

**Closed by seancpeters** 2018-08-31 01:34 UTC
