### ISSUE TITLE
Adding Custom Template Item

### ISSUE THREAD

**Issue by mgolois** [aspnet/Scaffolding#792] opened 2018-05-16 17:20 UTC
Hello,

In order to improve productivity, is it possible to add a another version of a Controller template (not editing existing, but adding a new one) eg: "MyControllerWithActions.cshtml" template. All the examples I saw were related to editing existing template.

Thanks

**Comment by vijayrkn** [comment] 2019-11-08 17:53
Closing as a dupe of this https://github.com/aspnet/Scaffolding/issues/938

**Closed by vijayrkn** 2019-11-08 17:53 UTC
