### ISSUE TITLE
MVC 6 Entity Scaffolding bug

### ISSUE THREAD

**Issue by bwoodard007** [aspnet/Scaffolding#247] opened 2016-06-05 18:54 UTC
``` c#
    public class Quiz
    {
        public int Id { get; set; }
        [Required, MaxLength(255)]
        public string Title { get; set; }
        [Required]
        public DateTime DateCreated { get; set; }
        public Difficulty DifficultyLevel { get; set; }
    }
    public enum Difficulty
    {
        Beginner = 1,
        Intermediate,
        Advanced
    }
   public class Question
    {
        public int Id { get; set; }
        [Required]
        public Quiz Quiz { get; set; }

        [Required]
        public int QuizId { get; set; }

        [Required]
        public string QuestionContent { get; set; }
    }

```

I created a new controller using MVC + Entity Framework, it generated the following code on Create:

``` c#
[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,QuestionContent,QuizId")] Question question)
        {
            if (ModelState.IsValid)
            {
                _context.Add(question);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["QuizId"] = new SelectList(_context.Quizzes, "Id", "Quiz", question.QuizId);
            return View(question);
        }
```

In my view 
``` html
@model MeMeA.Guru.Entities.Question

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Question</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="QuestionContent" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="QuestionContent" class="form-control" />
                <span asp-validation-for="QuestionContent" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="QuizId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="QuizId" class ="form-control" asp-items="ViewBag.QuizId"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
```

The view always generates an error
```
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.

Microsoft.AspNetCore.Mvc.Rendering.MultiSelectList.Eval(Object container, String expression)`
```

I just wanted to let you guys know this error occurs in the default code generation when adding a controller and view.

**Comment by dougbu** [comment] 2016-06-06 02:18
@bwoodard007 does the same exception occur in your `Create` action for an HTTP Get?

More generally, `_context.Quizzes` is probably `null` for some application-specific reason.

**Comment by bwoodard007** [comment] 2016-06-06 15:42
No it's not null, I stepped through with the debugger the actual error happens on the view.

**Comment by prafullbhosale** [comment] 2016-06-06 18:21
@bwoodard007 This was a known issue with scaffolding in preview2

The problem is the way the Select list is created in the controller. 

`ViewData["QuizId"] = new SelectList(_context.Quizzes, "Id", "Quiz", question.QuizId);`

This needs to change to 

`ViewData["QuizId"] = new SelectList(_context.Quizzes, "Id", "Title", question.QuizId);`

More details: https://github.com/aspnet/Scaffolding/issues/232

**Comment by bwoodard007** [comment] 2016-06-06 19:06
@prafullbhosale I see you've reopened it because that's the code the controller generated. Thanks for your help.

**Comment by prafullbhosale** [comment] 2016-06-06 19:09
@bwoodard007 The issue is marked closed as the fix is checked in. However the new packages are not available on nuget.org yet.

**Comment by barrytang** [comment] 2016-06-17 21:56
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=232605&fullScreen=false&_a=edit">232605</a>

**Comment by barrytang** [comment] 2016-06-21 20:44
This is fixed for the upcoming Dev14 release.

**Closed by barrytang** 2016-06-21 20:44 UTC
Labels: TFS Tracked
