### ISSUE TITLE
'A type with the name {FQN} does not exist at...'

### ISSUE THREAD

**Issue by bryanloeper** [aspnet/Scaffolding#288] opened 2016-08-16 03:49 UTC
Exact code I am having the issue with is available here: https://github.com/bryanloeper/Fallout4Checklist/commit/3d0cd8d0e3c43a70a5a1a97d028be24492a14e74

Key classes:
Fallout4Checklist > FO4 (Portable) > Entities > Locations > Location.cs
Fallout4Checklist > FO4.Web > Data > Fallout4Context.cs

![image](https://cloud.githubusercontent.com/assets/1320428/17687223/e95bc36e-6338-11e6-8304-b6bf9349aebe.png)
![image](https://cloud.githubusercontent.com/assets/1320428/17687229/f507570a-6338-11e6-9e51-ca7bc2daba84.png)
![image](https://cloud.githubusercontent.com/assets/1320428/17687237/08bf22aa-6339-11e6-8c4d-c43a196c9e58.png)
![image](https://cloud.githubusercontent.com/assets/1320428/17687242/10de7c38-6339-11e6-9af2-1bb31a7bc3b0.png)
![image](https://cloud.githubusercontent.com/assets/1320428/17687244/198903e4-6339-11e6-8f4e-74eea3bc0694.png)

**Visual Studio / Extension Version Info**
Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA436
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Microsoft Visual Studio Tools for Applications 2015   00322-80000-00000-AA436
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-80000-00000-AA436
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA436
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA436
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-80000-00000-AA436
Windows Phone SDK 8.0 - ENU

.ignore   1.2.67
A language service that makes it painless to handle all types of .ignore files such as .gitignore, .tfignore, etc.

Add New File   3.5
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2015.1   14.1.20810.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.1   14.0.20622.0
Azure App Service Tools v2.9.1

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.0.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Bundler & Minifier   2.1.279
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

CodeMaid   10.1.93
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

File Nesting   2.5.62
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Image Optimizer   3.6.93
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

Image Sprites   1.3.38
Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Markdown Editor   1.7.148
A full featured Markdown editor with live preview and syntax highligting. Supports GitHub flavored Markdown.

Microsoft .NET Core Tools (Preview 2)   14.1.20810.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure HDInsight HQL Service   2.0.6000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40701.9

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.175
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Package Installer   1.8.85
Makes it easier, faster and more convenient than ever to install Bower, npm, JSPM, TSD, Typings and NuGet packages to any project

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Analysis Services   13.0.1605.88
Microsoft SQL Server Analysis Services Designer 
Version 13.0.1605.88

SQL Server Compact & SQLite Toolbox   4.6.0
SQL Server Compact & SQLite Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

SQL Server Data Tools   14.0.60629.0
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 13.0.1601.5

SQL Server Reporting Services   13.0.1605.88
Microsoft SQL Server Reporting Services Designers 
Version 13.0.1605.88

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Universal Windows Apps   14.0.25527.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Accessibility Checker   1.3.32
The easiest way to perform accessibility checks on any ASP.NET web application. Fully customizable and support all the major international accessibility standards.

Web Compiler   1.11.319
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015.3   3.0.235
Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015

Xamarin   4.1.2.18 (fcbe082)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   6.1.2.21 (1cf254d)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   9.8.2.22 (f37444a)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by prafullbhosale** [comment] 2016-08-16 17:23
@bryanloeper There was an issue with scaffolding when the model was in a dependency. 
See #251 for more details. 
The issue is fixed in the dev branch. 
But for a workaround, you can move the model class to the web project for scaffolding and then move it back.

**Comment by bryanloeper** [comment] 2016-08-16 21:25
@prafullbhosale Thanks - that worked! Any ETA on when the dev branch will make it to a release? I was thinking it might be a different root cause since Tooling's Preview2 just got updated a few days ago.

**Comment by prafullbhosale** [comment] 2016-09-13 16:13
@bryanloeper Sorry for the delay in response here.
The fix is now available on nuget in version `1.0.0-preview2-update1`

**Closed by prafullbhosale** 2016-09-13 16:13 UTC
