### ISSUE TITLE
Reusing razor-markup in custom scaffolding templates

### ISSUE THREAD

**Issue by jarnmo** [aspnet/Scaffolding#969] opened 2019-03-21 08:53 UTC
I've used custom RazorPage templates fairly successfully, but one biggish issue is that I don't seem to be able to share pieces of razor markup in/between them. I looked into Partials, ViewComponents and the [@helper-workaround](https://github.com/aspnet/AspNetCore/issues/5110#issuecomment-440245705), but couldn't make any of them work.

Trying to use Partials via `@HTML` prints something along the lines of "The name 'HTML' doesn't exist.." when scaffolding. Using `<partial name=".." />` just prints the tag as is. ViewComponents seem to have the same issue: `@Component` doesn't exist at scaffold time. The `@helper`-workaround gives two compile time errors in the generated xPageModel.g.cshtml.cs: "The name 'PushWriter' does not exist in the current context" and the same for 'PopWriter'.

I guess it makes sense that `@HTML` doesn't exist here, because it's not a web context, but could `@Component` stuff exist at scaffold time? And should the `@helper`-workaround just work?

Or is there another possible way to reuse razor-markup in the scaffolding templates?

I tested this with 2.2.3.

**Comment by vijayrkn** [comment] 2019-11-08 18:24
Closing as a dupe of this https://github.com/aspnet/Scaffolding/issues/938

**Closed by vijayrkn** 2019-11-08 18:24 UTC
