### ISSUE TITLE
[Preview2-Validation] Scaffolding razor pages using EF CRUD generates _ValidationScriptsPartial

### ISSUE THREAD

**Issue by Eilon** [aspnet/Scaffolding#721] opened 2018-04-05 17:33 UTC
_From @kichalla on April 4, 2018 23:3_

Repro:
- Create a new `WebApplication` template based project (This should create `_ValidationScriptsPartial.cshtml` under `Pages\Shared` folder)
- Add the following class in `Data` folder
```c#
public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ZipCode { get; set; }
}
```
- Add a new folder `Customers` under `Pages` folder
- Right click on `Customers` folder | Add Razor Page.. | Razor Pages using EntityFramework (CRUD) | Add | Choose `Customer` model class and `ApplicationDbContext` | Add

**Expected**: `_ValidationScriptsPartial.cshtml` should not be regenerated as there is already one under `Pages\Shared` folder
**Actual**: A new `_ValidationScriptsPartial.cshtml` file is created under `Pages` folder.

_Copied from original issue: aspnet/templating#449_

**Comment by Eilon** [comment] 2018-04-05 17:33
Should this be in the Scaffolding repo?

**Comment by vijayrkn** [comment] 2019-11-09 01:09
Looks like this is fixed but the issue is not closed. Closing.

**Closed by vijayrkn** 2019-11-09 01:09 UTC
