### ISSUE TITLE
Unable to scaffold when using C# 7.1+ language features

### ISSUE THREAD

**Issue by MattCotterellNZ** [aspnet/Scaffolding#926] opened 2018-11-10 23:39 UTC
### Describe the bug
Currently I am unable to scaffold ASP.NET Core Identity 2.1 razor pages in a project that uses C# 7.1 features (via Visual Studio 2017 15.8.9) when I am using either of the following C# 7.1 features:

* `async Main()` in `program.cs`
* `default` literals (i.e. `string param = default` rather than `string param = default(string)`

I get the following error:

```
There was an error running the selected code generator:
'Failed to compile the project in memory
<path_to_cs_file>: error CSCS8107: Feature `default literal` is not available in C# 7.0. Please use language version 7.1 or greater.
<path_to_cs_file>: error CSCS8107: Feature `async main` is not available in C# 7.0. Please use language version 7.1 or greater.
error CS5001: Program does not contain a static 'Main' method suitable for an entry point'
```

Removing these features from my code results in the scaffolder running successfully. 

### To Reproduce
1. Using netcoreapp2.1 (`Microsoft.AspNetCore.App` without a pinned version in the `.csproj` file)
2. Enable C# 7.1 (or above) (i.e. `<LangVersion>7.2</LangVersion>`)
3. Use async main and default literal features in the project
4. Compile successfully
5. Try and scaffold identity ("Add > New Scaffold Item > Identity > All")
6. See error
7. Remove C# 7.1+ language features from project (leave enabled in the project)
8. Try and scaffold identity ("Add > New Scaffold Item > Identity > All")
9. Note that it is successful and without error

### Expected behavior
A C# 7.1 project that uses these features and compiles successfully should successfully scaffold ASP.NET Core Identity 2.1 pages.

### Additional context
```
> dotnet --info

.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\2.1.403\

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [c:\program files\dotnet\sdk]
  1.0.0-preview2-003156 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003156 [c:\program files\dotnet\sdk]
  1.0.0-preview2-1-003177 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-1-003177 [c:\program files\dotnet\sdk]
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.0.0-rc4-004771 [c:\program files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.0 [c:\program files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.3 [c:\program files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.0.4 [c:\program files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  1.1.0 [c:\program files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.10 [c:\program files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  1.1.11 [c:\program files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.2 [c:\program files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.0.3 [c:\program files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [c:\program files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [c:\program files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.101 [c:\program files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.102 [c:\program files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.103 [c:\program files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.104 [c:\program files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.200 [c:\program files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.201 [c:\program files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.202 [c:\program files\dotnet\sdk]
  2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008673 [c:\program files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.400 [c:\program files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.401 [c:\program files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.403 [c:\program files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-final [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by MattCotterellNZ** [comment] 2018-11-13 23:54
Since this has been transferred, it might be a duplicate of #834. Happy to close if that's the case.

**Comment by seancpeters** [comment] 2018-11-16 18:57
@MattCotterellNZ - yes this is a duplicate of #834

**Closed by seancpeters** 2018-11-16 18:57 UTC
