### ISSUE TITLE
Adapt to new project model 

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#281] opened 2016-07-28 18:23 UTC
Need to find alternatives to APIs provided by `Microsoft.DotNet.ProjectModel` and `Microsoft.DotNet.ProjectModel.Workspaces`

Scaffolding uses the above for the following information/ actions:
- References of the project
- Build path
- Target frameworks
- Project compilation
- Modifying project compilation
- Updating source code files

**Comment by prafullbhosale** [comment] 2016-07-29 20:33
Related aspnet/EntityFramework#6139

**Comment by mlorbetske** [comment] 2016-09-14 20:48
Duplicate of #298

**Closed by mlorbetske** 2016-09-14 20:48 UTC
