### ISSUE TITLE
Scaffold Identity omits custom ApplicationUser

### ISSUE THREAD

**Issue by blowdart** [aspnet/Scaffolding#839] opened 2018-07-19 18:02 UTC
_From @Ponant on July 19, 2018 15:25_

**Works**
1) New project 2.1 MVC with no auth
2) Scaffold identity and choose the plus button for the user class

![scaffoldidentity21](https://user-images.githubusercontent.com/19961806/42952012-cef98632-8b77-11e8-9c61-219423f81672.PNG)

The resulting code is expected because it refers to `ApplicationUser`

`    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
`
`                services.AddDefaultIdentity<ApplicationUser>()
`

**Does not work**
1) New project 2.1 MVC with no auth
2) Create a class ApplicationUser that derives from IdentityUser
`    public class ApplicationUser : IdentityUser
`
3) Scaffold identity and choose the **dropdown** button for the user class

![scaffoldidentity21bug](https://user-images.githubusercontent.com/19961806/42952344-8aa84c10-8b78-11e8-96d4-c37ede8b262c.PNG)

The resulting code is unexpected because it refers to `IdentityUser`. `ApplicationUser `is totally ignored

`    public class ApplicationDbContext : IdentityDbContext<IdentityUser>
`
`                services.AddDefaultIdentity<IdentityUser>()
`

Bug?

_Copied from original issue: aspnet/Identity#1886_

**Comment by seancpeters** [comment] 2018-07-19 18:53
@ponant - this issue is a duplicate of https://github.com/aspnet/Scaffolding/issues/761 and has been fixed here: https://github.com/aspnet/Scaffolding/pull/765

The fix is available in the 2.1 Microsoft.VisualStudio.Web.CodeGeneration.Design package, which ships with the 2.1 SDK.

**Comment by Ponant** [comment] 2018-07-19 18:57
@seancpeters , I have the 2.1 SDK. It is Microsoft.VisualStudio.Web.CodeGeneration.Design v2.1.1

**Comment by Ponant** [comment] 2018-07-19 19:08
![cmddotnetinfo](https://user-images.githubusercontent.com/19961806/42964622-df81bf90-8b97-11e8-90db-dd169968ead3.PNG)

**Comment by seancpeters** [comment] 2018-07-19 20:03
@Ponant  - sorry for the premature close on this issue. I'm also able to repro it with the 2.1.0 Design package. I'll update this thread when a fix is available.

**Comment by seancpeters** [comment] 2018-07-19 22:31
@Ponant - I've tracked down the root cause of this issue - it's in the VS integration of the identity scaffolder. When I know which release the fix will be available in, I'll update you here.

**Comment by Ponant** [comment] 2018-07-20 07:11
The same happens with the Razor Pages template

**Comment by seancpeters** [comment] 2018-07-20 17:59
@Ponant - could you provide more details about the problem you're seeing with the Razor Pages template? I'm not clear on the problem you're seeing there.

**Comment by Ponant** [comment] 2018-07-20 18:14
@seancpeters , I meant that the same problem is found when you use the Razor Page template in step 1 instead the MVC template.

**Comment by ASKemp** [comment] 2018-08-16 12:28
Adding to that, I already had a User class - the scaffolding assumes I want to use that without giving me the option to select the default (IdentityUser), so as not to conflict, and uses that class name in all the scaffolded code .
I had to do a directory comparison with/without my existing class to bring in IdentityUser alongside my existing User.
I'm assuming that's the point of the "User" class select box but, as above, mine was disabled.

**Comment by seancpeters** [comment] 2018-08-16 18:20
@ASKemp - The user class selection is only enabled when creating a new DataContext class, it is disabled when selecting an existing data context class.

When an existing data context class is chosen, the identity user associated with that data context class is used in scaffolding, because the data context is already setup to use the existing identity user. Here's an example of a the class declaration for a identity db context:
`public class WebApplication104IdentityContext : IdentityDbContext<MyUser>`
Here, `MyUser` is the existing identity user.


When creating a new identity data context when identity scaffolding, and not choosing a custom user class, the default IdentityUser is used, like this:
`WebApplication104IdentityContext2 : IdentityDbContext<IdentityUser>`

**Comment by ASKemp** [comment] 2018-08-16 23:16
Thanks., although i didn't have an identity user associated the class chosen. It would be good if the scaffolding tool pointed these things out.
Also, I found that the selected path of a new db context is not honoured and reverts to the default.

As you note, I found that if you select an existing db context then it wont allow you to specify a user class, if you create a new db context then you can (it does allow you to call it identityuser,  which causes conflicts) and it will extend identityuser with the new user class but uses this throughout your scaffolded code - I assume any areas that are not scaffolded also inherit the new user class name rather than relying on identityuser?
Could identityuser have been left as is but injected with the new user class instead of changing code references?

Many thanks.

**Comment by vijayrkn** [comment] 2019-11-08 17:48
@ASKemp  - Do you think there is anything left to address here? If yes, please re-open. 

Closing the issue since the initial reported issue is fixed.

**Closed by vijayrkn** 2019-11-08 17:48 UTC

**Comment by egocarib** [comment] 2022-07-19 00:24
Yes, I also have been struggling with this today. I had to scaffold and then manually find/replace all instances of `IdentityUser` with my custom `ApplicationUser`.
