### ISSUE TITLE
BUG: Scaffolding create wrong span elements.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Scaffolding#267] opened 2016-06-30 11:27 UTC
Scaffolding currently creates
```
 <span asp-validation-for="Name" class="text-danger" />
```
which is wrong and doesn't work.
should be:
```
 <span asp-validation-for="Name" class="text-danger"></span>
```

**Comment by prafullbhosale** [comment] 2016-06-30 16:44
Dupe of #227

**Closed** 2016-06-30 17:01 UTC
