### ISSUE TITLE
2.1.1 Version of the Microsoft.VisualStudio.Web.CodeGeneration.Utils nuget package breaks VSTS builds

### ISSUE THREAD

**Issue by aerostudios** [aspnet/Scaffolding#858] opened 2018-08-26 22:29 UTC
## Steps to reproduce:
1. Create an ASP.NET Core 2.1 project.
2. Submit that project to a VSTS build pipeline using a Hosted2017 agent

## Expected behavior:
Builds fine

## Actual behavior:
Fails with the following error:
error : Response status code does not indicate success: 400 (Bad Request - The package is invalid: The package version had build metadata.  We do not support versions with build metadata (VSTS Activity ID: 272E5937-0080-4FFA-AA01-D74C2C017EA8))

From the web project dependencies, the Microsoft.VisualStudio.Web.CodeGeneration.Utils nuget package is reliant on NuGet.Frameworks 4.7.0 which is a SemVer 2.0 package and not supported by the VSTS build pipeline.

Is there a solid reason to be dependent on the 4.7.0 version of the NuGet.Frameworks package?  All other Core packages use 4.0 (if they do).  Could you release a version of the Microsoft.VisualStudio.Web.CodeGeneration.Utils that is compatible with VSTS?

### Target framework(s):
2.1

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
2.1.2
### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
2.1.1

**Comment by vijayrkn** [comment] 2018-10-08 22:00
@aerostudios - Are you still running into this issue? If so, can you provide us with a sample project?

**Comment by vijayrkn** [comment] 2019-11-08 17:34
Closing since we were unable to reproduce this issue.

**Closed by vijayrkn** 2019-11-08 17:34 UTC
